.TH CYBERONIX 1 2023-02-06 "GNU" "Cyberonix User Manual"
.SH NAME
.B cyberonix \- 
.I A Complete Resource Hub For Cyber Security Community
.SH SYNOPSIS
.B cyberonix
.RI [ options ]
.RI "[\-ip " IP "]"
.RI "[\-r " Record "]"
.RI [ Argument ]..
.SH DESCRIPTION
.B Cyberonix
is an open source & free tool by 
.B Team Metaxone Solution. 
The tool at first is developed by a team of students as part of their Internship at 
.B Metaxone Solution 
after their Diploma in Cyber Security Training.

It is a complete resource hub for Cyber Security Community. Our aim is to make this tool an 1 stop solution for all the Hackers out there to get resources of various topics in Cyber Security. We will keep updating this tool & adding new & updated resources on the go.

Feel free to suggest any feature that you want to see in this tool, We will be happy to include that in our next update.


.SH OPTIONS



.B \-\-tools
,
.B \-t
To Directly Access Tools Option

.B \-\-cheatsheet
,
.B \-c
To Directly Access Cheatsheet Option

.B \-\-news
,
.B \-n 
.RI [ Date ]
To Directly Access News Option. Giving Date Is Optional And Date Will Be Given In The Format yyyy-mm-dd (like: --news 2023-02-06)

.B \-\-asnrecord
,
.B \-asn
To Get asn Record(example: -asn -ip 8.8.8.8)

.B \-\-dnsrecord
,
.B \-dns
To Get DNS Record(example: -dns -domain metaxonesolution.com --record TXT)

.B \-\-default-password-gen
,
.B \-pass
To Generate Random Password it will include all upper case lower case digits punctuation length will be 8 you can use --length <length> to give custom length (like -pass -L 10) (Recommended)

.B \-\-http-status
,
.B \-S
To Get Http Status Code Of A Domain like 200 404(example: -S -D google.com)

.B \-\-screenshot
,
.B \-s
To Get Screenshot Of Websites and it will save it to /Screenshot(example: -s -domain metaxonesolution.com)

.B \-\-remove-duplicate
,
.B \-rd
To Remove Duplicate From a file(example: -rd -f file.txt)

.B \-\-getip
,
.B \-gip
.RI [ domain ]
To Get Ip Of A Domain (example: -gip google.com)


.SH ARGUMENTS



.B \-\-domain
,
.B \-D
.RI [ domain ]
To Give Domain (example: -D google.com)

.B \-\-ip
,
.B \-ip
.RI [ IP ]
To Give IP (example: -ip 8.8.8.8)

.B \-\-record
,
.B \-r
.RI [ Record ]
To Give Record For DNSrecord Like: A,TXT,MX (Example: --record TXT)

.B \-\-upper
,
.B \-u
For Upper Case Character In Password

.B \-\-lower
,
.B \-l
For Lower Case Character In Password


.B \-\-digits
,
.B \-d
For digits in Password


.B \-\-punctuation
,
.B \-p
For Special character in Password


.B \-\-length
,
.B \-l
.RI [ Length ]
To Specify Length Of Password Default=8 (Example: -l 10)

.B \-\-checkpassword
,
.B \-C
To Check Your Generated Password

.B \-\-file
,
.B \-f
.RI [ location ]
To Give A File Input(example: -f /path/to/file)

.B \-\-output
,
.B \-o
.RI [ location ]
To Get Output In A File (example: -o /path/to/file)


.SH FILES
.TP
.I
/usr/bin/cyberonix

.SH BUGS
In the event that you encounter any bugs or issues, we encourage you to reach out to us through our GitHub repository at https://github.com/TeamMetaxone/Cyberonix/issues or by contacting us through our Discord server at https://discord.gg/eAzXRzCS6p. We welcome any feedback or suggestions you may have, and we are committed to addressing any concerns you may have in a timely and professional manner.

.SH COPYRIGHT
.PP
Copyright 2023 MetaxOne Solution. All rights reserved
https://metaxonesolution.com/

.SH CREDITS
.PP
We would like to acknowledge and express our gratitude to the talented and hardworking team at Metaxone for their exceptional work in developing the Cyberonix toolkit. Their dedication, creativity, and expertise have resulted in a powerful and innovative software tool that has the potential to make a significant impact in the field of cybersecurity. We extend our sincere thanks to the Metaxone team for their contributions and commitment to excellence.
.SH
.PP
MetaxOne Solution, Cyberonix
